[versions]
agp = "8.9.2"
javascriptengine = "1.0.0-rc01"
kotlin = "1.9.0"

[libraries]
androidx-javascriptengine = { module = "androidx.javascriptengine:javascriptengine", version.ref = "javascriptengine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

